# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
     - name: Docker Login

       uses: docker/login-action@v2.1.0
       with:
         username: manish3097

         password: Allohmora123

    

